# Generated by Django 5.0.4 on 2024-06-17 01:59

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Tài khoản ngân hàng')),
                ('id_card', models.CharField(blank=True, max_length=20, verbose_name='Căn cước công dân')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m', verbose_name='Ảnh đại diện')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tên đăng nhập')),
            ],
            options={
                'verbose_name': 'Quản lý và cấp quyền tài khoản',
                'verbose_name_plural': '1. Quản lý và cấp quyền tài khoản',
            },
        ),
    ]
