# Generated by Django 5.0.4 on 2024-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Thông tin tài khoản', 'verbose_name_plural': '1. Thông tin tài khoản'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Giỏ hàng cũ'),
        ),
    ]
