# Generated by Django 5.0.4 on 2024-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('du_lieu', models.CharField(max_length=255, verbose_name='Dữ liệu barcode')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
