# Generated by Django 5.0.4 on 2024-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0002_rename_address_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tài khoản ngân hàng'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Căn cước công dân'),
        ),
    ]
