# Generated by Django 5.0.4 on 2024-06-20 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0024_nhaphang_luot_thich_alter_nhaphang_tinh_trang'),
        ('VIIItratien', '0003_alter_shippingaddress_shipping_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('shipping_address_get', models.CharField(max_length=255, verbose_name='Địa chỉ nhận hàng')),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền đã trả')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập hóa đơn')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mã khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IIIquanlykho.nhaphang', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mã khách hàng')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VIIItratien.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng chi tiết',
            },
        ),
    ]
