# Generated by Django 5.0.4 on 2024-06-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0005_alter_itemorder_price_alter_itemorder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name_plural': 'Đơn hàng theo món'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Tổng đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_bank_account',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_email',
        ),
    ]
