# Generated by Django 5.0.4 on 2024-06-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0006_alter_itemorder_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address_get',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_get',
            new_name='shipping_address',
        ),
    ]
