# Generated by Django 5.0.4 on 2024-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0008_order_shipping_id_card_order_shipping_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_id_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=1500, verbose_name='Thông tin nhận hàng'),
        ),
    ]
