# Generated by Django 5.0.4 on 2024-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0009_remove_order_shipping_id_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='Đâ giao hàng'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá (đồng)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền phải trả'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập đơn hàng'),
        ),
    ]
