# Generated by Django 5.0.4 on 2024-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIIItratien', '0010_alter_order_options_order_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='Khách đã nhận hàng'),
        ),
    ]
