# Generated by Django 5.0.4 on 2024-05-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongTy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_ty', models.CharField(max_length=255, unique=True, verbose_name='Tên công ty')),
                ('ten_viet_tat', models.CharField(max_length=100, unique=True, verbose_name='Tên viết tắt')),
                ('logoCongTy', models.ImageField(blank=True, null=True, upload_to='congty/%Y/%m', verbose_name='Thêm Logo')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('hotline', models.CharField(max_length=15, verbose_name='Hotline')),
                ('kick_hoat_web', models.BooleanField(default=False, verbose_name='Hiển thị thông tin lên Website')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': '1. Công ty',
            },
        ),
        migrations.CreateModel(
            name='NhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhiem_vu', models.CharField(max_length=100, unique=True, verbose_name='Tên nhiệm vụ')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ nhân viên',
                'verbose_name_plural': '4. Nhiệm vụ nhân viên',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': '3. Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_nhanh', models.CharField(max_length=100, unique=True, verbose_name='Tên chi nhánh')),
                ('ten_viet_tat', models.CharField(max_length=100, unique=True, verbose_name='Tên viết tắt')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('hotline', models.CharField(max_length=15, verbose_name='Hotline')),
                ('cong_ty', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_nhanhs', to='Ithongtincongty.congty', verbose_name='Trực thuộc công ty')),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': '2. Chi nhánh',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=255, null=True, verbose_name='Tên nhân viên')),
                ('chi_nhanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhanvien', to='Ithongtincongty.chinhanh', verbose_name='Thuộc chi nhánh')),
                ('nhiem_vu', models.ManyToManyField(blank=True, related_name='nhanvien', to='Ithongtincongty.nhiemvu', verbose_name='Nhiệm vụ')),
            ],
            options={
                'verbose_name': 'Danh sách nhân viên',
                'verbose_name_plural': '5. Danh sách nhân viên',
            },
        ),
    ]
