# Generated by Django 5.0.4 on 2024-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithongtincongty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='so_thu_tu',
            field=models.CharField(blank='', default=0, editable=False, max_length=10, verbose_name='Số thứ tự'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='congty',
            name='so_thu_tu',
            field=models.CharField(blank='', default=0, editable=False, max_length=10, verbose_name='Số thứ tự'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='so_thu_tu',
            field=models.CharField(blank='', default=0, editable=False, max_length=10, verbose_name='Số thứ tự'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='so_thu_tu',
            field=models.CharField(blank='', default=0, editable=False, max_length=10, verbose_name='Số thứ tự'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phongban',
            name='so_thu_tu',
            field=models.CharField(blank='', default=0, editable=False, max_length=10, verbose_name='Số thứ tự'),
            preserve_default=False,
        ),
    ]
