# Generated by Django 5.0.4 on 2024-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithongtincongty', '0002_chinhanh_so_thu_tu_congty_so_thu_tu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinhanh',
            name='so_thu_tu',
            field=models.CharField(blank='', editable=False, max_length=10, verbose_name='STT'),
        ),
        migrations.AlterField(
            model_name='congty',
            name='so_thu_tu',
            field=models.CharField(blank='', editable=False, max_length=10, verbose_name='STT'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_thu_tu',
            field=models.CharField(blank='', editable=False, max_length=10, verbose_name='STT'),
        ),
        migrations.AlterField(
            model_name='nhiemvu',
            name='so_thu_tu',
            field=models.CharField(blank='', editable=False, max_length=10, verbose_name='STT'),
        ),
        migrations.AlterField(
            model_name='phongban',
            name='so_thu_tu',
            field=models.CharField(blank='', editable=False, max_length=10, verbose_name='STT'),
        ),
    ]
