# Generated by Django 5.0.4 on 2024-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithongtincongty', '0003_alter_chinhanh_so_thu_tu_alter_congty_so_thu_tu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='congty',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='phongban',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
    ]
