# Generated by Django 5.0.4 on 2024-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithongtincongty', '0004_chinhanh_kich_hoat_congty_kich_hoat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinhanh',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='congty',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nhiemvu',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='phongban',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
    ]
