# Generated by Django 5.0.4 on 2024-05-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithongtincongty', '0005_alter_chinhanh_kich_hoat_alter_congty_kich_hoat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='chi_nhanh',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhanvien', to='Ithongtincongty.chinhanh', verbose_name='Chi nhánh'),
        ),
    ]
