# Generated by Django 5.0.4 on 2024-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoSuuTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_bo_suu_tap', models.CharField(max_length=100, unique=True, verbose_name='Tên bộ sưu tập')),
                ('anh_dai_dien', models.ImageField(upload_to='bo_suu_tap', verbose_name='Tải ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Bộ sưu tập',
                'verbose_name_plural': '1. Bộ sưu tập',
            },
        ),
    ]
