# Generated by Django 5.0.4 on 2024-05-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IIIquanlykho', '0019_nhaphang_ton_kho'),
        ('IVdoitac', '0004_alter_khachhang_anh_dai_dien_alter_khachhang_email'),
        ('Ithongtincongty', '0006_alter_nhanvien_chi_nhanh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiGiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_giao_dich', models.CharField(max_length=255, verbose_name='Tên giao dịch')),
            ],
            options={
                'verbose_name': 'Danh mục giao dịch',
                'verbose_name_plural': '1. Danh mục giao dịch',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_created=True, editable=False, verbose_name='Ngày tạo')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('trang_thai_don_hang', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_giao_hang', 'Đang giao hàng'), ('da_hoan_thanh', 'Đã hoàn thành'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('tong_gia_tri', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng giá trị')),
                ('tam_ung', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền tạm ứng')),
                ('so_tien_con_lai', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền còn lại')),
                ('phuong_thuc_thanh_toan', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('chi_nhanh', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ithongtincongty.chinhanh')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVdoitac.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': '2. Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='DonHangChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('don_gia', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Đơn giá')),
                ('thanh_tien', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, verbose_name='Thành tiền')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIgiaodichkhach.donhang', verbose_name='Đơn hàng')),
                ('nhap_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IIIquanlykho.nhaphang', verbose_name='Nhập hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': '2b. Chi tiết đơn hàng',
            },
        ),
        migrations.AddField(
            model_name='donhang',
            name='san_pham',
            field=models.ManyToManyField(through='VIgiaodichkhach.DonHangChiTiet', to='IIIquanlykho.nhaphang'),
        ),
        migrations.CreateModel(
            name='DonHangLoaiGiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIgiaodichkhach.donhang')),
                ('loai_giao_dich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIgiaodichkhach.loaigiaodich')),
            ],
            options={
                'verbose_name': 'Đơn hàng - Loại giao dịch',
                'verbose_name_plural': '2a. Đơn hàng - Loại giao dịch',
            },
        ),
        migrations.AddField(
            model_name='donhang',
            name='loai_giao_dich',
            field=models.ManyToManyField(through='VIgiaodichkhach.DonHangLoaiGiaoDich', to='VIgiaodichkhach.loaigiaodich'),
        ),
    ]
