# Generated by Django 5.0.4 on 2024-05-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0020_alter_nhaphang_ton_kho'),
        ('IVdoitac', '0004_alter_khachhang_anh_dai_dien_alter_khachhang_email'),
        ('Ithongtincongty', '0006_alter_nhanvien_chi_nhanh'),
        ('VIgiaodichkhach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='chi_nhanh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ithongtincongty.chinhanh', verbose_name='Chi nhánh'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVdoitac.khachhang', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ngay_tao',
            field=models.DateTimeField(auto_created=True, editable=False, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='san_pham',
            field=models.ManyToManyField(through='VIgiaodichkhach.DonHangChiTiet', to='IIIquanlykho.nhaphang', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='donhangloaigiaodich',
            name='don_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIgiaodichkhach.donhang', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='donhangloaigiaodich',
            name='loai_giao_dich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIgiaodichkhach.loaigiaodich', verbose_name='Chọn giao dịch'),
        ),
    ]
