# Generated by Django 5.0.4 on 2024-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIgiaodichkhach', '0002_alter_donhang_chi_nhanh_alter_donhang_khach_hang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhangchitiet',
            name='don_gia',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='donhangchitiet',
            name='thanh_tien',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Thành tiền'),
        ),
    ]
