# Generated by Django 5.0.4 on 2024-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vgiavang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giavang',
            name='gia_vang',
            field=models.IntegerField(default=0, verbose_name='Giá vàng (1000 đồng)'),
        ),
    ]
