# Generated by Django 5.0.4 on 2024-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vgiavang', '0002_alter_giavang_gia_vang'),
    ]

    operations = [
        migrations.AddField(
            model_name='giavang',
            name='gia_vang_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá vàng (1000 đồng)'),
        ),
    ]
