# Generated by Django 5.0.4 on 2024-05-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0012_alter_nhaphang_nhom_hang'),
        ('Vgiavang', '0004_remove_giavang_gia_vang_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giavang',
            name='gia_vang',
        ),
        migrations.AddField(
            model_name='giavang',
            name='gia_ban',
            field=models.IntegerField(default=0, verbose_name='Giá bán'),
        ),
        migrations.AddField(
            model_name='giavang',
            name='gia_mua',
            field=models.IntegerField(default=0, verbose_name='Giá mua'),
        ),
        migrations.AlterField(
            model_name='giavang',
            name='loai_vang',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gia_vangs', to='IIIquanlykho.loaivang', verbose_name='Loại vàng'),
        ),
    ]
