# Generated by Django 5.0.4 on 2024-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vgiavang', '0005_remove_giavang_gia_vang_giavang_gia_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giavang',
            name='gia_ban',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='giavang',
            name='gia_mua',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá mua'),
        ),
    ]
