# Generated by Django 5.0.4 on 2024-05-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='hinh_anh',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai_vang',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='ma_vach',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='nhom_hang',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='ten_chi_nhanh',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='ten_san_pham',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='tinh_trang',
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san_pham', verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='loai_vang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIIquanlykho.loaivang', verbose_name='Loại vàng'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='ma_vach',
            field=models.ImageField(blank=True, upload_to='ma_vach', verbose_name='Mã vạch'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='mo_ta',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='nhom_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIIquanlykho.nhomhang', verbose_name='Thuộc nhóm hàng'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='ten_san_pham',
            field=models.CharField(default=0, max_length=255, verbose_name='Tên sản phẩm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(default='Còn hàng', max_length=255, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='loaivang',
            name='nhom_vang',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IIIquanlykho.nhomvang', verbose_name='Thuộc nhóm vàng'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='quay_lon',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IIIquanlykho.quaylon', verbose_name='Thuộc quầy lớn'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='quay_nho',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIIquanlykho.quaynho', verbose_name='Quầy nhỏ'),
        ),
        migrations.AlterField(
            model_name='quaynho',
            name='quay_lon',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quay_nhos', to='IIIquanlykho.quaylon', verbose_name='Thuộc quầy lớn'),
        ),
    ]
