# Generated by Django 5.0.4 on 2024-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0003_loaivang_so_thu_tu_nhaphang_so_thu_tu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaivang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhomhang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='nhomvang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='quaylon',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='quaynho',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, editable=False, verbose_name='Kích hoạt'),
        ),
    ]
