# Generated by Django 5.0.4 on 2024-05-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0004_loaivang_kich_hoat_nhaphang_kich_hoat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaivang',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='nhomhang',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='nhomvang',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='quaylon',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='quaynho',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='hoat_dong',
        ),
    ]
