# Generated by Django 5.0.4 on 2024-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0005_remove_loaivang_hoat_dong_remove_nhomhang_hoat_dong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_nha_cung_cap', models.CharField(max_length=255, unique=True, verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': '6.1. Nhà cung cấp',
            },
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='ma_san_pham',
            field=models.CharField(default=0, editable=False, max_length=13, verbose_name='Mã sản phẩm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loaivang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nhomhang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nhomvang',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='quaylon',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='quaynho',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='kich_hoat',
            field=models.BooleanField(blank='', default=True, verbose_name='Kích hoạt'),
        ),
    ]
