# Generated by Django 5.0.4 on 2024-05-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0007_alter_nhaphang_ma_vach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NhaCungCap',
        ),
    ]
