# Generated by Django 5.0.4 on 2024-05-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0008_delete_nhacungcap'),
        ('IVdoitac', '0002_rename_ten_nha_cung_cap_nhacungcap_nha_cung_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='nha_cung_cap',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IVdoitac.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
    ]
