# Generated by Django 5.0.4 on 2024-05-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0009_nhaphang_nha_cung_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomhang',
            name='ma_nhom_hang',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Mã nhóm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhomhang',
            name='quay_nho',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhom_hangs', to='IIIquanlykho.quaynho', verbose_name='Quầy nhỏ'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='quay_lon',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IIIquanlykho.quaylon', verbose_name='Quầy lớn'),
        ),
    ]
