# Generated by Django 5.0.4 on 2024-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0010_nhomhang_ma_nhom_hang_nhomhang_quay_nho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhaphang',
            name='ma_vach',
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tem',
            field=models.ImageField(blank=True, editable=False, upload_to='tem', verbose_name='Tem'),
        ),
    ]
