# Generated by Django 5.0.4 on 2024-05-19 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0011_remove_nhaphang_ma_vach_nhaphang_tem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhaphang',
            name='nhom_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIIquanlykho.nhomhang', verbose_name='Nhóm hàng'),
        ),
    ]
