# Generated by Django 5.0.4 on 2024-05-20 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0012_alter_nhaphang_nhom_hang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanPham',
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='ngay_nhap',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Ngày nhập hàng'),
        ),
    ]
