# Generated by Django 5.0.4 on 2024-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0013_delete_sanpham_nhaphang_ngay_nhap'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='cong_ban',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Công bán'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='cong_von',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Công vốn'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='gia_ban_mon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán món'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='so_luong',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tien_hot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền hột'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tl_hot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Trọng hột/SP'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tl_vang',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6, verbose_name='Trọng vàng'),
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='tl_vang_hot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Trọng lượng vàng + hột'),
        ),
    ]
