# Generated by Django 5.0.4 on 2024-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0015_nhaphang_so_lo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(choices=[('Chờ duyệt nhập', 'Chờ duyệt nhập'), ('Còn hàng', 'Còn hàng'), ('Hết hàng', 'Hết hàng')], default='Chờ duyệt nhập', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
