# Generated by Django 5.0.4 on 2024-05-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0016_alter_nhaphang_tinh_trang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhaphang',
            name='ten_nhan_vien',
        ),
        migrations.AddField(
            model_name='nhaphang',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên nhập hàng'),
        ),
    ]
