# Generated by Django 5.0.4 on 2024-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0017_remove_nhaphang_ten_nhan_vien_nhaphang_nhan_vien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaivang',
            name='do_uu_tien',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='loaivang',
            name='doi',
            field=models.PositiveIntegerField(default=0, verbose_name='Đổi'),
        ),
        migrations.AlterField(
            model_name='loaivang',
            name='tygia_max',
            field=models.PositiveIntegerField(default=0, verbose_name='% Tỷ giá max'),
        ),
        migrations.AlterField(
            model_name='loaivang',
            name='tygia_min',
            field=models.PositiveIntegerField(default=0, verbose_name='% Tỷ giá min'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='so_luong',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(choices=[('cho_duyet_nhap', 'Chờ duyệt nhập'), ('con_hang', 'Còn hàng'), ('het_hang', 'Hết hàng')], default='Chờ duyệt nhập', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='quaynho',
            name='trong_luong_khay_gram',
            field=models.PositiveIntegerField(default=0, verbose_name='Trọng lượng khay gram'),
        ),
        migrations.AlterField(
            model_name='quaynho',
            name='trong_luong_khay_ly',
            field=models.PositiveIntegerField(default=0, verbose_name='Trọng lượng khay ly'),
        ),
    ]
