# Generated by Django 5.0.4 on 2024-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0018_alter_loaivang_do_uu_tien_alter_loaivang_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='ton_kho',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Số lượng tồn kho'),
        ),
    ]
