# Generated by Django 5.0.4 on 2024-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0019_nhaphang_ton_kho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhaphang',
            name='ton_kho',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Tồn kho'),
        ),
    ]
