# Generated by Django 5.0.4 on 2024-05-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0020_alter_nhaphang_ton_kho'),
        ('IIcauhinhtrangchu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='bo_suu_tap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIcauhinhtrangchu.bosuutap', verbose_name='Hiển thị trong bộ sưu tập'),
        ),
    ]
