# Generated by Django 5.0.4 on 2024-05-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0021_nhaphang_bo_suu_tap'),
        ('IIcauhinhtrangchu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='da_ban',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Đã bán'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='bo_suu_tap',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhap_hangs', to='IIcauhinhtrangchu.bosuutap', verbose_name='Hiển thị trong bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(choices=[('Còn hàng', 'Còn hàng'), ('Còn hàng', 'Hết hàng')], default='Còn hàng', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='ton_kho',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Tồn kho'),
        ),
    ]
