# Generated by Django 5.0.4 on 2024-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0022_nhaphang_da_ban_alter_nhaphang_bo_suu_tap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhaphang',
            name='da_ban',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='SL bán'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(choices=[('con_hang', 'Còn hàng'), ('het_hang', 'Hết hàng')], default='con_hang', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='ton_kho',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='SL tồn kho'),
        ),
    ]
