# Generated by Django 5.0.4 on 2024-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIIquanlykho', '0023_alter_nhaphang_da_ban_alter_nhaphang_tinh_trang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaphang',
            name='luot_thich',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Khởi tạo lượt like'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='tinh_trang',
            field=models.CharField(choices=[('Còn hàng', 'Còn hàng'), ('Hết hàng', 'Hết hàng')], default='Còn hàng', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
