# Generated by Django 5.0.4 on 2024-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_giao_dich', models.CharField(max_length=255, verbose_name='Tên giao dịch')),
            ],
            options={
                'verbose_name': 'Danh mục giao dịch',
                'verbose_name_plural': '1. Danh mục giao dịch',
            },
        ),
    ]
