# Generated by Django 5.0.4 on 2024-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_nha_cung_cap', models.CharField(max_length=255, unique=True, verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': '1. Nhà cung cấp',
            },
        ),
        migrations.CreateModel(
            name='NhaVanChuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_nha_van_chuyen', models.CharField(max_length=255, unique=True, verbose_name='Nhà vận chuyển')),
            ],
            options={
                'verbose_name': 'Nhà vận chuyển',
                'verbose_name_plural': '2. Nhà vận chuyển',
            },
        ),
        migrations.CreateModel(
            name='ThoNgoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thu_tu', models.CharField(blank='', editable=False, max_length=10, verbose_name='STT')),
                ('kich_hoat', models.BooleanField(blank='', default=True, verbose_name='Kích hoạt')),
                ('ten_tho', models.CharField(max_length=255, unique=True, verbose_name='Tên thợ')),
            ],
            options={
                'verbose_name': 'Thợ ngoài',
                'verbose_name_plural': '3. Thợ ngoài',
            },
        ),
    ]
