# Generated by Django 5.0.4 on 2024-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IVdoitac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhacungcap',
            old_name='ten_nha_cung_cap',
            new_name='nha_cung_cap',
        ),
        migrations.RenameField(
            model_name='nhavanchuyen',
            old_name='ten_nha_van_chuyen',
            new_name='nha_van_chuyen',
        ),
    ]
