# Generated by Django 5.0.4 on 2024-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IVdoitac', '0003_khachhang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='khach/%Y/%m', verbose_name='Tải ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
